### ISSUE TITLE
[Build] A recent trip installing this 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#24]
I did a setup on a VM I have 

here is the ouput

first of all..

```bash
$ uname -aimnoprsv
Linux test 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

```txt
ASUS P8Z68-Z Pro Gen3 w/ 32gb Micron 16JTF1G64AZ-1G6E1 and an LGA1155 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

BIOS 3202  from 02/17/2012
```

```bash
$ python3 setup.py
Traceback (most recent call last):
  File "/home/gbowne1/Documents/learn_python/setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "/home/gbowne1/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

~/Documents/json-maestro
$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: black in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (23.3.0)
Requirement already satisfied: flake8 in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (5.0.4)
Requirement already satisfied: pytest in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (7.4.4)
Requirement already satisfied: pytest-cov in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: pytest-mock in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (3.11.1)
Requirement already satisfied: pylint in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.17.4)
Collecting pyright (from -r requirements.txt (line 7))
  Downloading pyright-1.1.384-py3-none-any.whl.metadata (6.7 kB)
ERROR: Ignored the following versions that require a different python version: 0.0.2 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement pylance (from versions: none)
ERROR: No matching distribution found for pylance
~/Documents/json-maestro
$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/gbowne1/Documents/json-maestro
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of jsonmaestro to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'jsonmaestro' requires a different Python: 3.7.3 not in '>=3.10'
~/Documents/json-maestro
$ python --version
Python 3.12.5
~/Documents/json-maestro
$ python3 --version
Python 3.12.5
~/Documents/json-maestro
$ cd src
~/Documents/json-maestro/src
$ cd jsonmaestro
~/Documents/json-maestro/src/jsonmaestro
$ python3 main.py
Traceback (most recent call last):
  File "/home/gbowne1/Documents/json-maestro/src/jsonmaestro/main.py", line 2, in <module>
    from jsonmaestro.jsonmaestro import load_json, load_jsonc,remove_comments,remove_duplicate_keys,add_schema_keys, sort_json_keys,save_json
ModuleNotFoundError: No module named 'jsonmaestro.jsonmaestro'; 'jsonmaestro' is not a package
gbowne1@gregbowne:~/Documents/json-maestro/src/jsonmaestro
$ python3 jsonmaestro.py
~/Documents/json-maestro/src/jsonmaestro
$ python3 helpers.py
~/Documents/json-maestro/src/jsonmaestro
$ python3 helpers.py
```

This may not uncover much here but just thought I would include a run on machine I use often.

**Comment by shoshta73** [comment]
Can you you give me output of `which python` and `ls -AlF /usr/bin | grep python` ?

**Comment by gbowne1** [comment]
Sure.. on this particular system it is

```bash
admsys@test:~
$ which python
/usr/local/bin/python
admsys@test:~
$ whereis python
python: /usr/bin/python3.7-dbg /usr/bin/python3.7 /usr/bin/python3.7dm /usr/bin/python /usr/bin/python3.7m /usr/bin/python3.7dm-config /usr/bin/python3.7-dbg-config /usr/bin/python2.7 /usr/lib/python3.7 /usr/lib/python2.7 /etc/python3.7 /etc/python /etc/python2.7 /usr/local/bin/python /usr/local/bin/python3.12 /usr/local/bin/python3.12-config /usr/local/lib/python3.7 /usr/local/lib/python3.12 /usr/local/lib/python2.7 /usr/include/python3.7dm /usr/include/python3.7m /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz
admsys@test:~
$ whereis python3
python3: /usr/bin/python3.7-dbg /usr/bin/python3.7 /usr/bin/python3.7dm /usr/bin/python3.7m /usr/bin/python3.7dm-config /usr/bin/python3 /usr/bin/python3.7-dbg-config /usr/lib/python3.7 /usr/lib/python3 /etc/python3.7 /etc/python3 /usr/local/bin/python3.12 /usr/local/bin/python3 /usr/local/bin/python3.12-config /usr/local/lib/python3.7 /usr/local/lib/python3.12 /usr/include/python3.7dm /usr/include/python3.7m /usr/share/python3 /usr/share/man/man1/python3.1.gz
admysys@test:~
$ ls -AlF /usr/bin | grep python
lrwxrwxrwx 1 root    root           26 Mar  7  2019 dh_pypy -> ../share/dh-python/dh_pypy*
-rwxr-xr-x 1 root    root         1056 Mar  4  2019 dh_python2*
lrwxrwxrwx 1 root    root           29 Mar  7  2019 dh_python3 -> ../share/dh-python/dh_python3*
-rwxr-xr-x 1 root    root         2336 Jun 20  2017 dh_python3-ply*
lrwxrwxrwx 1 root    root           23 Mar 23  2024 pdb2.7 -> ../lib/python2.7/pdb.py*
lrwxrwxrwx 1 root    root           23 Mar 23  2024 pdb3.7 -> ../lib/python3.7/pdb.py*
lrwxrwxrwx 1 root    root           31 Mar 26  2019 py3versions -> ../share/python3/py3versions.py*
lrwxrwxrwx 1 root    root           26 Mar  7  2019 pybuild -> ../share/dh-python/pybuild*
lrwxrwxrwx 1 root    root            7 Mar  4  2019 python -> python2*
lrwxrwxrwx 1 root    root            9 Mar  4  2019 python2 -> python2.7*
-rwxr-xr-x 1 root    root      3685224 Mar 23  2024 python2.7*
lrwxrwxrwx 1 root    root            9 Mar 26  2019 python3 -> python3.7*
-rwxr-xr-x 2 root    root      4874240 Mar 23  2024 python3.7*
lrwxrwxrwx 1 root    root           11 Mar 23  2024 python3.7-dbg -> python3.7dm*
lrwxrwxrwx 1 root    root           37 Mar 23  2024 python3.7-dbg-config -> x86_64-linux-gnu-python3.7-dbg-config*
-rwxr-xr-x 1 root    root     18902912 Mar 23  2024 python3.7dm*
lrwxrwxrwx 1 root    root           35 Mar 23  2024 python3.7dm-config -> x86_64-linux-gnu-python3.7dm-config*
-rwxr-xr-x 2 root    root      4874240 Mar 23  2024 python3.7m*
lrwxrwxrwx 1 root    root           13 Mar 26  2019 python3-dbg -> python3.7-dbg*
lrwxrwxrwx 1 root    root           20 Mar 26  2019 python3-dbg-config -> python3.7-dbg-config*
lrwxrwxrwx 1 root    root           11 Mar 26  2019 python3dm -> python3.7dm*
lrwxrwxrwx 1 root    root           18 Mar 26  2019 python3dm-config -> python3.7dm-config*
lrwxrwxrwx 1 root    root           10 Mar 26  2019 python3m -> python3.7m*
lrwxrwxrwx 1 root    root           29 Mar  4  2019 pyversions -> ../share/python/pyversions.py*
lrwxrwxrwx 1 root    root           35 Mar 23  2024 x86_64-linux-gnu-python3.7-dbg-config -> x86_64-linux-gnu-python3.7dm-config*
-rwxr-xr-x 1 root    root         3280 Mar 23  2024 x86_64-linux-gnu-python3.7dm-config*
lrwxrwxrwx 1 root    root           37 Mar 26  2019 x86_64-linux-gnu-python3-dbg-config -> x86_64-linux-gnu-python3.7-dbg-config*
lrwxrwxrwx 1 root    root           35 Mar 26  2019 x86_64-linux-gnu-python3dm-config -> x86_64-linux-gnu-python3.7dm-config*
```

**Comment by shoshta73** [comment]
Since its debian (debian 10 if im not mistaken) there is high probability that update-alternatives is pointing to the python3.7 binary in /usr/bin even tho /usr/bin should be superseded by /usr/local/bin

**Comment by gbowne1** [comment]
Yes, exactly.

I was just thinking here about edge cases here where the user may not have either 3.8 or 3.10.

Yes Debian 10 using apt

```shell
$ apt --version
apt 1.8.2.3 (amd64)
```

**Comment by shoshta73** [comment]
Can you try and set required python version to 3.7 and report what happens?

**Comment by gbowne1** [comment]
yeah, I changed the pyproject.toml and setup.py to require version 3.7 and ran it.. this is what happened


again the system here is:
$ uname -aimnoprsv
Linux test 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

```shell
gbowne1@gregbowne:~/Documents/learn_python
$ python3 setup.py
Traceback (most recent call last):
  File "/home/gbowne1/Documents/learn_python/setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "/home/gbowne1/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

```shell
admsys@test:~/Documents/learn_python
$ python3 setup.py
Traceback (most recent call last):
  File "/home/gbowne1/Documents/learn_python/setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "/home/gbowne1/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
test@test:~/Documents/learn_python
$ pip install -r requirements.txtpip install -r requirements.txtpip install -r requirements.txtpip install -r requirements.txt^C
admsys@test:~/Documents/learn_python
$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: black in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (23.3.0)
Requirement already satisfied: flake8 in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (5.0.4)
Requirement already satisfied: pytest in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (7.4.4)
Requirement already satisfied: pytest-cov in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: pytest-mock in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (3.11.1)
Requirement already satisfied: pylint in /home/gbowne1/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.17.4)
Collecting pyright (from -r requirements.txt (line 7))
  Downloading pyright-1.1.384-py3-none-any.whl.metadata (6.7 kB)
ERROR: Ignored the following versions that require a different python version: 0.0.2 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement pylance (from versions: none)
ERROR: No matching distribution found for pylance
admsys@test:~/Documents/learn_python
$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/gbowne1/Documents/learn_python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: jsonmaestro
  Building wheel for jsonmaestro (pyproject.toml) ... done
  Created wheel for jsonmaestro: filename=jsonmaestro-0.0.1-py3-none-any.whl size=6769 sha256=d8818c3fdd13c6b0973048c9092f374ed2bf7bc25df16433ed78977d71f480c4
  Stored in directory: /tmp/pip-ephem-wheel-cache-wp3wifef/wheels/d7/ac/6f/ba1e77ccdfddeaba1930feb91823984f63dbcb2451a758a6ab
Successfully built jsonmaestro
Installing collected packages: jsonmaestro
Successfully installed jsonmaestro-0.0.1
admsys@test:~/Documents/learn_python
$ 
```

And today I tested on the bleeding edge VM on my fully loaded Dell R720 which has almost nightly versions of packages and libraries. And that system works fine with 3.7, 3.8, 3.10, 3.12.. as I have all of those versions installed.

**Comment by gbowne1** [comment]
I have no idea why it only liked pip install . instead of with requirements.txt

**Comment by gbowne1** [comment]
Pylance in VSCode is still hollering at me in red squigglies about the words setup and find_packages from setuptools import setup, find_packages` in setup.py

setup says:

```
Type of "setup" is partially unknown
  Type of "setup" is "(**attrs: Unknown) -> Distribution"Pylance[reportUnknownVariableType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownVariableType)
(function) def setup(**attrs: Unknown) -> Distribution
```

find_packages says 

```
Type of "find_packages" is partially unknown
  Type of "find_packages" is "(where: str = '.', exclude: Unknown = (), include: Unknown = ('*', )) -> list[Unknown]"Pylance[reportUnknownVariableType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownVariableType)
(variable) def find_packages(
    where: str = '.',
    exclude: Unknown = (),
    include: Unknown = ('*', )
) -> list[Unknown]
Return a list all Python packages found within directory 'where'

'where' is the root directory which will be searched for packages. It should be supplied as a "cross-platform" (i.e. URL-style) path; it will be converted to the appropriate local path syntax.
```

**Comment by gbowne1** [comment]
Seems to me that most of this is fixed with the current PR's.

**Comment by gbowne1** [comment]
Closing this as complete.
